---
# firefox tasks

# install firefox
- name: Check if firefox is installed
  command: ls /Applications/Firefox.app/
  register: firefox_exists
  ignore_errors: True
  tags:
    - firefox

- name: Download firefox
  when: firefox_exists|failed
  get_url: url={{ firefox_install_url }} dest=/tmp/firefox.dmg mode=0440
  tags:
    - firefox

- name: Mount firefox image
  when: firefox_exists|failed
  command: hdiutil attach /tmp/firefox.dmg
  tags:
    - firefox

- name: Copy firefox app to Applications directory
  when: firefox_exists|failed
  copy: src="/Volumes/Firefox/Firefox.app/" dest=/Applications
  tags:
    - firefox

- name: Unmount firefox image
  when: firefox_exists|failed
  command: hdiutil detach /Volumes/Firefox/
  tags:
    - firefox