---

- name: Get dotfiles repo
  git: repo={{ dotfiles_repo }} dest={{ workspace_dir }}/dotfiles

- name: Install dotfiles
  command: "{{ dotfiles_install_cmd }}"
  args:
    chdir: "{{ dotfiles_dir }}"
