---

- name: get dotfiles
  git: repo={{ dotfiles_repo }} dest=/tmp/dotfiles

- name: install dotfiles
  command: "{{ dotfiles_install_cmd }}"
  args:
    chdir: /tmp/dotfiles

- name: Update .gitconfig with name
  replace: dest="{{ home_dir }}/.gitconfig" regexp="%%name%%" replace="{{ first_name }} {{ last_name }}"

- name: Update .gitconfig with email
  replace: dest="{{ home_dir }}/.gitconfig" regexp="%%email%%" replace="{{ email }}"
