---

docker_default_containers:
  - ignigena/drupal-kitematic
docker_machine_version: "0.5.4"
docker_toolbox_version: "1.9.1f"
docker_toolbox_repo: "https://github.com/docker/toolbox"
docker_toolbox_install_url: "{{ docker_toolbox_repo }}/releases/download/v{{ docker_toolbox_repo }}/DockerToolbox-{{ docker_toolbox_repo }}.pkg"
