---

- name: Check if git is installed
  command: git --version
  register: git_exists
  tags:
    - git

- name: Download git
  when: git_exists|failed
  get_url: url={{ git_install_url }} dest=/tmp/git.dmg mode=0440
  tags:
    - git

- name: Mount git image
  when: git_exists|failed
  command: hdiutil attach /tmp/git.dmg
  tags:
    - git

- name: Install git
  when: git_exists|failed
  command: installer -pkg {{ git_volume }}/git-{{ git_version }}-intel-universal-mavericks.pkg -target /
  sudo: yes
  tags:
    - git

- name: Unmount git image
  when: git_exists|failed
  command: hdiutil detach {{ git_volume }}
  tags:
    - git