---
# subl tasks

# install sublime
- name: check if sublime is installed
  command: subl -v
  register: subl_exists
  ignore_errors: True
  tags:
    - subl

- name: download sublime
  # when: subl_exists|failed
  get_url: url={{ subl_install_url }} dest=/tmp/subl.dmg mode=0440
  tags:
    - subl

- name: Mount sublime image
  # when: subl_exists|failed
  command: hdiutil attach /tmp/subl.dmg
  tags:
    - subl

- name: Copy sublime app to Applications directory
  # when: subl_exists|failed
  copy: src="/Volumes/Sublime Text/Sublime Text.app" dest=/Applications
  tags:
    - subl

- name: Unmount sublime image
  # when: subl_exists|failed
  command: hdiutil detach /Volumes/Sublime\ Text
  tags:
    - subl

# subl command
- name: Subl command symlink
  # when: subl_exists|failed
  file: src="/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" dest=/usr/local/bin/subl state=link
  tags:
    - subl

# install package control
- name: download package control
  # when: subl_exists|failed
  get_url: url={{ package_control_url }} dest="/tmp/Package Control.sublime-package" mode=0440
  tags:
    - subl

- name: Copy package control to installed packages
  # when: subl_exists|failed
  copy: src="/tmp/Package Control.sublime-package" dest="{{ subl_app_folder }}/Installed Packages/"
  tags:
    - subl

# default packages
- name: SublimeLinter3
  git: repo="git@github.com:SublimeLinter/SublimeLinter3.git" dest="{{ subl_app_folder }}Packages/SublimeLinter" update=yes
  tags:
    - subl
    - subl-packages
