---

- name: check if docker is installed
  command: docker-machine -v | grep {{ docker_machine_version }}
  register: docker_exists
  tags:
    - docker

- name: download docker toolbox
  when: docker_exists | failed
  get_url: url={{ docker_toolbox_install_url }} dest=/tmp/docker.pkg mode=0440
  tags:
    - docker

- name: install docker toolbox
  when: docker_exists | failed
  command: installer -pkg /tmp/node.pkg -target /
  sudo: yes
  tags:
    - docker

- name: check if machine is running
  command: docker-machine ls | grep -i default | grep -i running
  register: virtualbox_running

- name: start machine
  when: virtualbox_running | failed
  command: docker-machine start default
