---

- name: ssh dir
  file:
    path={{ home_dir }}/.ssh
    state=directory
  tags:
    - base

- name: Project workspace
  file:
    path={{ workspace_dir }}
    state=directory
  tags:
    - base

- name: User tmp dir
  file:
    path="{{ home_dir }}/tmp"
    state=directory
  tags:
    - base
