---

- name: ssh dir
  file:
    path={{ home_dir }}/.ssh
    state=directory

- name: Site workspace
  file:
    path={{ workspace_dir }}
    state=directory

- name: User tmp dir
  file:
    path="{{ home_dir }}/tmp"
    state=directory

- name: Own usr/local/bin
  file: path=/usr/local/bin owner={{ whoami }}
